### ISSUE TITLE
[start-preset] JSON files not tracked on build task

### ISSUE THREAD

**Issue by atilafassina** [nextools/metarepo#233]
Hey, I've found a little issue on the latest `r11y`.
The `axe-rules.json` file which is used internally to generate the reports isn't landing on the built package.

From what I can see, the build task on `start-preset` is tracking only JavaScript and TypeScript files, no JSON.

Is this something desired to have for every package, or should there be a workaround for r11y only?
- if for every package: on the `start-preset` or `babel-config` ?

Thanks for the help! :)

**Comment by deepsweet** [comment]
Hey!

This one is indeed a mistake, `axe-rules.json` should have been copied into the `build/` folder.

Instead of handling `.json` manually we have an abstract [`buildAssets`](https://github.com/nextools/metarepo/blob/b84629ccc7f3ac5920db091703843e5ed88aa06c/packages/nextools/start-preset/src/build.ts#L140-L142) thing, take a look at my linked fix commit above.

Just published as `r11y@0.1.4`.

**Comment by atilafassina** [comment]
thanks a bunch for doing it so quickly!
